'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Contensive.Addons.Rss.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 
        '''Option Explicit
        '''&apos;
        '''#Const DebugBuild = False
        '''&apos;
        '''&apos;=======================================================================
        '''&apos;   sitepropertyNames
        '''&apos;=======================================================================
        '''&apos;
        '''Public Const siteproperty_serverPageDefault_name = &quot;serverPageDefault&quot;
        '''Public Const siteproperty_serverPageDefault_defaultValue = &quot;index.php&quot;
        '''&apos;
        '''&apos;=======================================================================
        '''&apos;   content replacements
        '''&apos;====================================== [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property LegacyVb6_ccCommonModule() As String
            Get
                Return ResourceManager.GetString("LegacyVb6_ccCommonModule", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to  
        '''Option Explicit
        '''&apos;
        '''&apos;========================================================================
        '''&apos;   kma defined errors
        '''&apos;       1000-1999 Contensive
        '''&apos;       2000-2999 Datatree
        '''&apos;
        '''&apos;   see kmaErrorDescription() for transations
        '''&apos;========================================================================
        '''&apos;
        '''Const Error_DataTree_RootNodeNext = 2000
        '''Const Error_DataTree_NoGoNext = 2001
        '''&apos;
        '''&apos;========================================================================
        '''&apos;
        '''&apos;========================================== [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property LegacyVb6_KmaCommonModule() As String
            Get
                Return ResourceManager.GetString("LegacyVb6_KmaCommonModule", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to select top 1 m.name as personName, o.organizationName 
        '''from ccmembers m left join organizations o on o.id=m.organizationId
        '''where o.id={0}.
        '''</summary>
        Friend ReadOnly Property sampleSql() As String
            Get
                Return ResourceManager.GetString("sampleSql", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
